name: Iron Broom
maintainer: https://github.com/fjakop
description: |
  Cleanup terminated standalone containers, dangling volumes and images
version: 0.0.1
category: Monitoring
projectURL: https://github.com/fjakop/iron-broom
